import React, { useState, useEffect, useRef } from "react";
import { supabase } from "./supabaseClient";
import { jsPDF } from "jspdf";

const DRAFT_STORAGE_KEY = "aerolog-draft";

function normalizeBullets(text) {
  return text
    .split(/\r?\n/)
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) return "";
      if (/^[\-•]\s*/.test(trimmed))
        return `• ${trimmed.replace(/^[\-•]\s*/, "")}`;
      return `• ${trimmed}`;
    })
    .join("\n");
}

function getEntryDescription(entry) {
  return entry.description || entry.work_description || "";
}

function createPdfFromEntry(doc, entry, pageWidth, pageHeight, margin) {
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text("AEROLOG PRO", margin, y);
  y += 28;

  doc.setFontSize(14);
  doc.text("AVIATION MAINTENANCE ENTRY", margin, y);
  y += 22;

  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(1.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 40);
  doc.text("GENERAL INFORMATION", margin, y);
  y += 18;

  const rows = [
    ["Entry No", entry.id || "N/A"],
    ["Date", entry.date || "-"],
    ["Aircraft", entry.aircraft || "-"],
    ["Registration", entry.registration || "-"],
    ["ATA Category", entry.ata_category || "-"],
    ["Hours", entry.hours ? `${entry.hours} hrs` : "-"],
    ["Supervisor", entry.supervisor || "-"],
    ["Work Order", entry.work_order || "-"],
  ];

  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(79, 89, 102);
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(String(value), margin + 96, y, { maxWidth: maxWidth - 96 });
    y += 16;
  });

  y += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 40);
  doc.text("WORK DESCRIPTION", margin, y);
  y += 18;

  const description = normalizeBullets(
    getEntryDescription(entry) || "No work description provided.",
  );
  const descriptionLines = doc.splitTextToSize(description, maxWidth);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(37, 47, 70);
  doc.text(descriptionLines, margin + 8, y);
  y += descriptionLines.length * 15 + 14;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 40);
  doc.text("TOOLS USED", margin, y);
  y += 18;

  const toolsLines = doc.splitTextToSize(String(entry.tools || "-"), maxWidth);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(37, 47, 70);
  doc.text(toolsLines, margin + 8, y);
  y += toolsLines.length * 15 + 14;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 40);
  doc.text("REFERENCE", margin, y);
  y += 18;

  const referenceLines = doc.splitTextToSize(String(entry.reference || "-"), maxWidth);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(37, 47, 70);
  doc.text(referenceLines, margin + 8, y);
  y += referenceLines.length * 15 + 18;

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  const footer = `Generated by AeroLog Pro • ${new Date().toISOString()}`;
  doc.text(footer, margin, y);
  doc.text(
    `Document ID: ${entry.id || "N/A"}`,
    pageWidth - margin - doc.getTextWidth(`Document ID: ${entry.id || "N/A"}`),
    y,
  );
}

function buildImageFromEntry(entry) {
  const width = 1200;
  const margin = 60;
  const lineHeight = 30;
  const rows = [
    { text: "AEROLOG PRO", style: "title" },
    { text: "AVIATION MAINTENANCE ENTRY", style: "subtitle" },
    { text: "" },
    { text: `Entry No: ${entry.id || "N/A"}`, style: "label" },
    { text: "" },
    { text: `Date: ${entry.date || "-"}`, style: "field" },
    { text: `Aircraft: ${entry.aircraft || "-"}`, style: "field" },
    { text: `Registration: ${entry.registration || "-"}`, style: "field" },
    { text: `ATA Category: ${entry.ata_category || "-"}`, style: "field" },
    {
      text: `Hours: ${entry.hours ? `${entry.hours} hrs` : "-"}`,
      style: "field",
    },
    { text: `Supervisor: ${entry.supervisor || "-"}`, style: "field" },
    { text: `Work Order: ${entry.work_order || "-"}`, style: "field" },
    { text: "" },
    { text: "WORK DESCRIPTION", style: "section" },
    ...normalizeBullets(
      getEntryDescription(entry) || "No work description provided.",
    )
      .split(/\r?\n/)
      .map((line) => ({ text: line, style: "body" })),
    { text: "" },
    { text: "TOOLS USED", style: "section" },
    { text: entry.tools || "-", style: "body" },
    { text: "" },
    { text: "REFERENCE", style: "section" },
    { text: entry.reference || "-", style: "body" },
    { text: "" },
    {
      text: `Generated by AeroLog Pro • ${new Date().toISOString()}`,
      style: "footer",
    },
  ];

  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  const textWidth = width - margin * 2;
  let height = margin + lineHeight;

  rows.forEach((item) => {
    const font =
      item.style === "title"
        ? "bold 34px Inter, Arial"
        : item.style === "subtitle"
          ? "600 18px Inter, Arial"
          : item.style === "section"
            ? "bold 16px Inter, Arial"
            : item.style === "footer"
              ? "12px Inter, Arial"
              : "16px Inter, Arial";
    ctx.font = font;
    const widthEstimate = ctx.measureText(item.text).width;
    const wrapLines = Math.max(1, Math.ceil(widthEstimate / textWidth));
    height += wrapLines * lineHeight;
  });
  height += margin;
  canvas.width = width;
  canvas.height = height;

  ctx.fillStyle = "#f8fafc";
  ctx.fillRect(0, 0, width, height);
  let y = margin + 34;

  rows.forEach((item) => {
    const font =
      item.style === "title"
        ? "bold 34px Inter, Arial"
        : item.style === "subtitle"
          ? "600 18px Inter, Arial"
          : item.style === "section"
            ? "bold 16px Inter, Arial"
            : item.style === "footer"
              ? "12px Inter, Arial"
              : "16px Inter, Arial";
    ctx.font = font;
    if (item.text === "") {
      y += lineHeight / 1.5;
      return;
    }
    ctx.fillStyle = item.style === "footer" ? "#64748b" : "#0f172a";
    ctx.fillText(item.text, margin, y);
    y += lineHeight;
  });

  return canvas.toDataURL("image/png");
}

export default function Logbook() {
  const [entries, setEntries] = useState([]);
  const [newEntry, setNewEntry] = useState({
    date: "",
    aircraft: "",
    registration: "",
    work_order: "",
    ata_category: "",
    description: "",
    tools: "",
    reference: "",
    hours: "",
    supervisor: "",
  });
  const [editingEntryId, setEditingEntryId] = useState(null);
  const [saving, setSaving] = useState(false);
  const [toast, setToast] = useState("");
  const [search, setSearch] = useState("");
  const [draftAvailable, setDraftAvailable] = useState(false);
  const [routePath, setRoutePath] = useState(window.location.pathname);
  const [theme, setTheme] = useState("dark");
  const descRef = useRef(null);

  const themeVars =
    theme === "light"
      ? {
          panelBg: "#FFFFFF",
          panelBorder: "#CBD5E1",
          muted: "#475569",
          accent: "#0EA5E9",
        }
      : {
          panelBg: "#111827",
          panelBorder: "#1F2937",
          muted: "#94A3B8",
          accent: "#38BDF8",
        };

  const filteredEntries = entries.filter((entry) => {
    const q = search.toLowerCase();
    return (
      entry.aircraft?.toLowerCase().includes(q) ||
      entry.registration?.toLowerCase().includes(q) ||
      entry.ata_category?.toLowerCase().includes(q) ||
      entry.supervisor?.toLowerCase().includes(q) ||
      entry.date?.toLowerCase().includes(q)
    );
  });

  useEffect(() => {
    loadEntries();
    loadDraft();
    window.onpopstate = () => setRoutePath(window.location.pathname);
  }, []);

  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(""), 3000);
    return () => clearTimeout(timer);
  }, [toast]);

  useEffect(() => {
    const interval = setInterval(() => {
      if (
        newEntry.date ||
        newEntry.aircraft ||
        newEntry.registration ||
        newEntry.description
      ) {
        window.localStorage.setItem(
          DRAFT_STORAGE_KEY,
          JSON.stringify(newEntry),
        );
        setDraftAvailable(true);
      }
    }, 30000);
    return () => clearInterval(interval);
  }, [newEntry]);

  async function loadEntries() {
    try {
      const { data, error } = await supabase
        .from("logbook_entries")
        .select(
          "id,date,aircraft,registration,work_order,ata_category,description,tools,reference,hours,supervisor,created_at",
        )
        .order("created_at", { ascending: false });
      if (error) throw error;
      setEntries(data || []);
    } catch (err) {
      console.error(err);
      setToast(err?.message || "Could not load saved entries.");
    }
  }

  function loadDraft() {
    const raw = window.localStorage.getItem(DRAFT_STORAGE_KEY);
    if (!raw) return;
    const draft = JSON.parse(raw);
    if (draft && Object.keys(draft).length) {
      setDraftAvailable(true);
      setToast("Draft available. Restore to continue.");
    }
  }

  function restoreDraft() {
    const raw = window.localStorage.getItem(DRAFT_STORAGE_KEY);
    if (!raw) return;
    setNewEntry(JSON.parse(raw));
    setDraftAvailable(false);
    setToast("Draft restored.");
  }

  function clearDraft() {
    window.localStorage.removeItem(DRAFT_STORAGE_KEY);
    setDraftAvailable(false);
    setToast("Draft cleared.");
  }

  async function createEntry(e) {
    e.preventDefault();
    setSaving(true);
    try {
      const descriptionValue = newEntry.description;
      if (
        !newEntry.date ||
        !newEntry.aircraft ||
        !newEntry.registration ||
        !descriptionValue
      ) {
        throw new Error(
          "Date, aircraft, registration, and work description are required.",
        );
      }
      const payload = {
        date: newEntry.date,
        aircraft: newEntry.aircraft,
        registration: newEntry.registration,
        work_order: newEntry.work_order,
        ata_category: newEntry.ata_category,
        description: descriptionValue,
        tools: newEntry.tools,
        reference: newEntry.reference,
        hours: Number(newEntry.hours) || 0,
        supervisor: newEntry.supervisor,
        created_at: new Date().toISOString(),
      };
      Object.keys(payload).forEach(
        (key) => payload[key] === undefined && delete payload[key],
      );
      const { error } = await supabase
        .from("logbook_entries")
        .insert([payload]);
      if (error) throw error;
      setToast("✓ Entry saved successfully.");
      setNewEntry({
        date: "",
        aircraft: "",
        registration: "",
        work_order: "",
        ata_category: "",
        description: "",
        tools: "",
        reference: "",
        hours: "",
        supervisor: "",
      });
      clearDraft();
      await loadEntries();
    } catch (err) {
      console.error(err);
      setToast(
        err?.message ||
          "Failed to save entry. Please check your internet connection.",
      );
    } finally {
      setSaving(false);
    }
  }

  async function updateEntry(e) {
    e.preventDefault();
    if (!editingEntryId) return;
    setSaving(true);
    try {
      const descriptionValue = newEntry.description;
      const payload = {
        date: newEntry.date,
        aircraft: newEntry.aircraft,
        registration: newEntry.registration,
        work_order: newEntry.work_order,
        ata_category: newEntry.ata_category,
        description: descriptionValue,
        tools: newEntry.tools,
        reference: newEntry.reference,
        hours: Number(newEntry.hours) || 0,
        supervisor: newEntry.supervisor,
      };
      Object.keys(payload).forEach(
        (key) => payload[key] === undefined && delete payload[key],
      );
      const { error } = await supabase
        .from("logbook_entries")
        .update(payload)
        .eq("id", editingEntryId);
      if (error) throw error;
      setToast("✓ Entry updated successfully");
      setNewEntry({
        date: "",
        aircraft: "",
        registration: "",
        work_order: "",
        ata_category: "",
        description: "",
        tools: "",
        reference: "",
        hours: "",
        supervisor: "",
      });
      setEditingEntryId(null);
      await loadEntries();
    } catch (err) {
      console.error(err);
      setToast("Failed to update entry.");
    } finally {
      setSaving(false);
    }
  }

  async function deleteEntry(id) {
    if (!confirm("Delete this entry?")) return;
    try {
      const { error } = await supabase
        .from("logbook_entries")
        .delete()
        .eq("id", id);
      if (error) throw error;
      setToast("Entry deleted");
      await loadEntries();
    } catch (err) {
      console.error(err);
      setToast("Failed to delete entry.");
    }
  }

  function editEntry(entry) {
    setEditingEntryId(entry.id);
    setNewEntry({
      date: entry.date || "",
      aircraft: entry.aircraft || "",
      registration: entry.registration || "",
      work_order: entry.work_order || "",
      ata_category: entry.ata_category || "",
      description: entry.description || entry.work_description || "",
      tools: entry.tools || "",
      reference: entry.reference || "",
      hours: entry.hours?.toString() || "",
      supervisor: entry.supervisor || "",
    });
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function viewEntry(entry) {
    window.history.pushState({}, "", `/entry/${entry.id}`);
    setRoutePath(`/entry/${entry.id}`);
  }

  function navigate(path) {
    window.history.pushState({}, "", path);
    setRoutePath(path);
  }

  function exportEntryPdf(entry, filename) {
    const doc = new jsPDF("p", "pt", "a4");
    createPdfFromEntry(
      doc,
      entry,
      doc.internal.pageSize.getWidth(),
      doc.internal.pageSize.getHeight(),
      40,
    );
    // Prefer opening/sharing a blob URL on mobile browsers where direct
    // downloads may be blocked; fall back to doc.save when needed.
    try {
      const blob = doc.output("blob");
      const file = new File([blob], filename, { type: "application/pdf" });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        navigator.share({ files: [file], title: filename });
        return;
      }
      const url = URL.createObjectURL(blob);
      const win = window.open(url, "_blank");
      if (!win) {
        const link = document.createElement("a");
        link.href = url;
        link.download = filename;
        link.click();
      }
      setTimeout(() => URL.revokeObjectURL(url), 15000);
    } catch (err) {
      doc.save(filename);
    }
  }

  function exportAllEntriesPdf() {
    if (!entries.length) return setToast("No entries to export.");
    const doc = new jsPDF("p", "pt", "a4");
    entries.forEach((entry, index) => {
      if (index > 0) doc.addPage();
      createPdfFromEntry(
        doc,
        entry,
        doc.internal.pageSize.getWidth(),
        doc.internal.pageSize.getHeight(),
        40,
      );
    });
    try {
      const blob = doc.output("blob");
      const filename = "aerolog-entries.pdf";
      const file = new File([blob], filename, { type: "application/pdf" });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        navigator.share({ files: [file], title: filename });
        return;
      }
      const url = URL.createObjectURL(blob);
      const win = window.open(url, "_blank");
      if (!win) {
        const link = document.createElement("a");
        link.href = url;
        link.download = "aerolog-entries.pdf";
        link.click();
      }
      setTimeout(() => URL.revokeObjectURL(url), 15000);
    } catch (err) {
      doc.save("aerolog-entries.pdf");
    }
  }

  function exportEntryImage(entry, filename) {
    const dataUrl = buildImageFromEntry(entry);
    const link = document.createElement("a");
    link.href = dataUrl;
    link.download = filename;
    link.click();
  }

  function exportFormPdf() {
    exportEntryPdf(
      { ...newEntry, id: editingEntryId || "draft" },
      "aerolog-entry.pdf",
    );
  }

  function exportFormImage() {
    exportEntryImage(
      { ...newEntry, id: editingEntryId || "draft" },
      "aerolog-entry.png",
    );
  }

  const routeEntryId = routePath.startsWith("/entry/")
    ? routePath.replace("/entry/", "")
    : null;
  const routeEntry = routeEntryId
    ? entries.find((entry) => entry.id?.toString() === routeEntryId)
    : null;

  return (
    <div
      className={`aerolog-root ${theme === "dark" ? "theme-dark" : "theme-light"}`}
    >
      <div
        className="topbar"
        style={{ borderBottom: `3px solid ${themeVars.accent}` }}
      >
        <div className="topbar-inner">
          <div className="brand">
            <div className="brand-sub">✈ AEROLOG PRO</div>
            <div className="brand-title">Aviation Maintenance Logbook</div>
          </div>
          <div className="topbar-actions">
            <span className="topbar-date">
              {new Date().toLocaleDateString()}
            </span>
            <button
              className="primary-btn"
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
            >
              {theme === "dark" ? "🌞 Light" : "🌙 Dark"}
            </button>
          </div>
        </div>
      </div>

      <div className="page-content">
        <div className="page-header">
          <div>
            <h1>AeroLog Pro v2</h1>
            <p>
              Save, search, and export aviation maintenance documentation with
              professional formatting.
            </p>
          </div>
          {toast && <div className="toast-message">{toast}</div>}
        </div>

        {routePath === "/" || routePath === "/entries" ? (
          <div className="form-grid">
            <section className="card glass-card">
              <div className="section-header">
                <div>
                  <div className="section-tag">NEW ENTRY</div>
                  <h2>Save Maintenance Records</h2>
                </div>
                <div className="draft-controls">
                  {draftAvailable && (
                    <button className="secondary-btn" onClick={restoreDraft}>
                      Restore Draft
                    </button>
                  )}
                  <button className="secondary-btn" onClick={clearDraft}>
                    Clear Draft
                  </button>
                </div>
              </div>

              <form onSubmit={editingEntryId ? updateEntry : createEntry}>
                <div className="form-row">
                  <div className="field-group">
                    <label className="field-label">
                      Date <span className="required">*</span>
                    </label>
                    <input
                      className="input"
                      placeholder="YYYY-MM-DD"
                      value={newEntry.date}
                      onChange={(e) =>
                        setNewEntry((prev) => ({
                          ...prev,
                          date: e.target.value,
                        }))
                      }
                    />
                  </div>
                  <div className="field-group">
                    <label className="field-label">
                      Aircraft <span className="required">*</span>
                    </label>
                    <input
                      className="input"
                      placeholder="Aircraft model"
                      value={newEntry.aircraft}
                      onChange={(e) =>
                        setNewEntry((prev) => ({
                          ...prev,
                          aircraft: e.target.value,
                        }))
                      }
                    />
                  </div>
                </div>
                <div className="form-row">
                  <div className="field-group">
                    <label className="field-label">
                      Registration <span className="required">*</span>
                    </label>
                    <input
                      className="input"
                      placeholder="Tail number"
                      value={newEntry.registration}
                      onChange={(e) =>
                        setNewEntry((prev) => ({
                          ...prev,
                          registration: e.target.value,
                        }))
                      }
                    />
                  </div>
                  <div className="field-group">
                    <label className="field-label">ATA Category</label>
                    <input
                      className="input"
                      placeholder="ATA chapter or code"
                      value={newEntry.ata_category}
                      onChange={(e) =>
                        setNewEntry((prev) => ({
                          ...prev,
                          ata_category: e.target.value,
                        }))
                      }
                    />
                  </div>
                </div>
                <div className="field-group">
                  <label className="field-label">Work Order</label>
                  <input
                    className="input"
                    placeholder="Work order number"
                    value={newEntry.work_order}
                    onChange={(e) =>
                      setNewEntry((prev) => ({
                        ...prev,
                        work_order: e.target.value,
                      }))
                    }
                  />
                </div>
                <div className="field-group">
                  <label className="field-label">
                    Work Description <span className="required">*</span>
                  </label>
                  <textarea
                    className="textarea"
                    ref={descRef}
                    rows={6}
                    placeholder="Use bullets or short paragraphs"
                    value={newEntry.description}
                    onChange={(e) =>
                      setNewEntry((prev) => ({
                        ...prev,
                        description: e.target.value,
                      }))
                    }
                  />
                </div>
                <div className="form-row">
                  <div className="field-group">
                    <label className="field-label">Tools</label>
                    <input
                      className="input"
                      placeholder="Tools used"
                      value={newEntry.tools}
                      onChange={(e) =>
                        setNewEntry((prev) => ({
                          ...prev,
                          tools: e.target.value,
                        }))
                      }
                    />
                  </div>
                  <div className="field-group">
                    <label className="field-label">Reference</label>
                    <input
                      className="input"
                      placeholder="Job card / reference"
                      value={newEntry.reference}
                      onChange={(e) =>
                        setNewEntry((prev) => ({
                          ...prev,
                          reference: e.target.value,
                        }))
                      }
                    />
                  </div>
                </div>
                <div className="form-row">
                  <div className="field-group">
                    <label className="field-label">Hours</label>
                    <input
                      className="input"
                      placeholder="Hours"
                      type="number"
                      value={newEntry.hours}
                      onChange={(e) =>
                        setNewEntry((prev) => ({
                          ...prev,
                          hours: e.target.value,
                        }))
                      }
                    />
                  </div>
                  <div className="field-group">
                    <label className="field-label">Supervisor</label>
                    <input
                      className="input"
                      placeholder="Supervisor name"
                      value={newEntry.supervisor}
                      onChange={(e) =>
                        setNewEntry((prev) => ({
                          ...prev,
                          supervisor: e.target.value,
                        }))
                      }
                    />
                  </div>
                </div>
                <div className="button-row">
                  <button
                    type="button"
                    className="secondary-btn"
                    onClick={exportFormPdf}
                  >
                    Export Draft PDF
                  </button>
                  <button
                    type="button"
                    className="secondary-btn"
                    onClick={exportFormImage}
                  >
                    Export Draft Image
                  </button>
                  <button type="submit" className="primary-btn">
                    {saving
                      ? "Saving..."
                      : editingEntryId
                        ? "Update Entry"
                        : "💾 Save Entry"}
                  </button>
                </div>
              </form>
            </section>

            <section className="card recent-entries">
              <div className="section-header">
                <div>
                  <div className="section-tag">ENTRY HISTORY</div>
                  <h2>Recent Entries</h2>
                </div>
                <div className="draft-controls">
                  <button
                    className="secondary-btn"
                    onClick={exportAllEntriesPdf}
                  >
                    Export All PDF
                  </button>
                </div>
              </div>

              <div className="search-box">
                <input
                  className="input"
                  placeholder="Search aircraft, date, ATA, supervisor"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                />
              </div>

              {filteredEntries.length === 0 ? (
                <div className="empty-state">
                  No entries found. Save an entry to populate history.
                </div>
              ) : (
                filteredEntries.map((entry) => (
                  <div key={entry.id} className="entry-card">
                    <div className="entry-card-top">
                      <div>
                        <div className="entry-title">Entry #{entry.id}</div>
                        <div className="entry-subtitle">
                          {entry.ata_category || "ATA Not Set"} ·{" "}
                          {entry.date || "Date Not Set"}
                        </div>
                      </div>
                      <div className="entry-hours">{entry.hours || 0} hrs</div>
                    </div>
                    <div className="entry-preview">
                      {normalizeBullets(getEntryDescription(entry))}
                    </div>
                    <div className="entry-actions">
                      <button
                        className="secondary-btn"
                        onClick={() => viewEntry(entry)}
                      >
                        View
                      </button>
                      <button
                        className="secondary-btn"
                        onClick={() => editEntry(entry)}
                      >
                        Edit
                      </button>
                      <button
                        className="secondary-btn"
                        onClick={() =>
                          exportEntryPdf(entry, `entry-${entry.id}.pdf`)
                        }
                      >
                        Export PDF
                      </button>
                      <button
                        className="secondary-btn"
                        onClick={() =>
                          exportEntryImage(entry, `entry-${entry.id}.png`)
                        }
                      >
                        Export Image
                      </button>
                      <button
                        className="delete-btn"
                        onClick={() => deleteEntry(entry.id)}
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                ))
              )}
            </section>
          </div>
        ) : routeEntry ? (
          <section className="card glass-card detail-card">
            <div className="detail-topbar">
              <div>
                <div className="section-tag">ENTRY DETAIL</div>
                <h2>Entry #{routeEntry.id}</h2>
              </div>
              <button
                className="primary-btn"
                onClick={() => navigate("/entries")}
              >
                Back to history
              </button>
            </div>
            <div className="detail-grid">
              <div>
                <div className="detail-label">Date</div>
                <div>{routeEntry.date || "-"}</div>
              </div>
              <div>
                <div className="detail-label">Aircraft</div>
                <div>{routeEntry.aircraft || "-"}</div>
              </div>
              <div>
                <div className="detail-label">Registration</div>
                <div>{routeEntry.registration || "-"}</div>
              </div>
              <div>
                <div className="detail-label">ATA Category</div>
                <div>{routeEntry.ata_category || "-"}</div>
              </div>
              <div>
                <div className="detail-label">Hours</div>
                <div>{routeEntry.hours || 0} hrs</div>
              </div>
              <div>
                <div className="detail-label">Supervisor</div>
                <div>{routeEntry.supervisor || "-"}</div>
              </div>
            </div>
            <div className="detail-section">
              <div className="detail-label">Work Description</div>
              <pre className="detail-text">
                {normalizeBullets(getEntryDescription(routeEntry))}
              </pre>
            </div>
            <div className="detail-section">
              <div className="detail-label">Tools Used</div>
              <div>{routeEntry.tools || "-"}</div>
            </div>
            <div className="detail-section">
              <div className="detail-label">Reference</div>
              <div>{routeEntry.reference || "-"}</div>
            </div>
          </section>
        ) : (
          <div className="card">Entry not found.</div>
        )}
      </div>
    </div>
  );
}
