-- Supabase/PostgreSQL schema for AeroLog Pro logbook_entries
-- Use this file to create the table in Supabase SQL Editor or via psql.

CREATE TABLE IF NOT EXISTS public.logbook_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  aircraft text NOT NULL,
  registration text NOT NULL,
  work_order text,
  ata_category text,
  work_description text NOT NULL,
  tools text,
  reference text,
  hours numeric DEFAULT 0,
  supervisor text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Trigger to keep updated_at in sync on row updates.
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON public.logbook_entries;
CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.logbook_entries
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
