-- Supabase/PostgreSQL schema for AeroLog Pro logbook_entries
-- Use this file to create the tables in Supabase SQL Editor or via psql.

CREATE TABLE IF NOT EXISTS public.logbook_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  aircraft text NOT NULL,
  registration text NOT NULL,
  work_order text,
  ata_category text,
  work_description text NOT NULL,
  tools text,
  reference text,
  hours numeric DEFAULT 0,
  supervisor text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.generator_sessions (
  id uuid PRIMARY KEY,
  user_id uuid,
  session_name text NOT NULL DEFAULT 'Untitled Session',
  min_value integer NOT NULL,
  max_value integer NOT NULL,
  total_numbers integer NOT NULL,
  generated_count integer NOT NULL DEFAULT 0,
  remaining integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.generated_numbers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES public.generator_sessions(id) ON DELETE CASCADE,
  generated_number integer NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  is_checked boolean NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX IF NOT EXISTS generated_numbers_session_number_idx
  ON public.generated_numbers (session_id, generated_number);

ALTER TABLE public.generator_sessions
ADD COLUMN IF NOT EXISTS session_name text DEFAULT 'Untitled Session';

ALTER TABLE public.generated_numbers
ADD COLUMN IF NOT EXISTS is_checked boolean DEFAULT false;

-- Trigger to keep updated_at in sync on row updates.
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON public.logbook_entries;
CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.logbook_entries
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS set_generator_sessions_updated_at ON public.generator_sessions;
CREATE TRIGGER set_generator_sessions_updated_at
BEFORE UPDATE ON public.generator_sessions
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
